= TOFS: A pattern for using SaltStack

.Authors
[format="psv", separator="|", frame="all", grid="all", float="left", options="header", cols="<.<20h,<.<25d,<.<35d,>.<20d", width="100"]
|===
<.^|
<.^|Person
<.^|Contact
>.^|Date

|Authored by
|Roberto Moreda
|moreda@allenta.com
|29/12/2014

|Modified by
|Daniel Dehennin
|daniel.dehennin@baby-gnu.org
|07/02/2019

|Modified by
|Imran Iqbal
|https://github.com/myii
|23/02/2019
|===

All that follows is a proposal based on my experience with
http://www.saltstack.com/[SaltStack]. The good thing of a piece of
software like this is that you can "bend it" to suit your needs in many
possible ways, and this is one of them. All the recommendations and
thoughts are given "as it is" with no warranty of any type.

// This `toc` will not show up in GitHub directly, only in the GitHub pages.
// Antora applies all of the `toc` settings when rendering the HTML.
toc::[]

== Usage of values in pillar vs templates in `file_roots`

Among other functions, the _master_ (or _salt-master_) serves files to
the _minions_ (or _salt-minions_). The
http://docs.saltstack.com/en/latest/ref/file_server/file_roots.html[file_roots]
is the list of directories used in sequence to find a file when a minion
requires it: the first match is served to the minion. Those files could
be
http://docs.saltstack.com/en/latest/topics/tutorials/starting_states.html[state
files] or configuration templates, among others.

Using SaltStack is a simple and effective way to implement configuration
management, but even in a
http://en.wikipedia.org/wiki/Multitenancy[non-multitenant] scenario, it
is not a good idea to generally access some data (e.g. the database
password in our http://www.zabbix.com/[Zabbix] server configuration file
or the private key of our http://nginx.org/en/[Nginx] TLS certificate).

To avoid this situation we can use the
http://docs.saltstack.com/en/latest/topics/pillar/[pillar mechanism],
which is designed to provide controlled access to data from the minions
based on some selection rules. As pillar data could be easily integrated
in the
http://docs.saltstack.com/en/latest/topics/tutorials/pillar.html[Jinja]
templates, it is a good mechanism to store values to be used in the
final rendering of state files and templates.

There are a variety of approaches on the usage of pillar and templates
as seen in the
https://github.com/saltstack-formulas[saltstack-formulas]' repositories.
https://github.com/saltstack-formulas/nginx-formula/pull/18[Some]
https://github.com/saltstack-formulas/php-formula/pull/14[developments]
stress the initial purpose of pillar data into a storage for most of the
possible variables for a determined system configuration. This, in my
opinion, is shifting too much load from the original template files
approach. Adding up some
https://github.com/spsoit/nginx-formula/blob/81de880fe0276dd9488ffa15bc78944c0fc2b919/nginx/ng/files/nginx.conf[non-trivial Jinja]
code as essential part of composing the state file definitely
makes SaltStack state files (hence formulas) more difficult to read. The
extreme of this approach is that we could end up with a new render
mechanism, implemented in Jinja, storing everything needed in pillar
data to compose configurations. Additionally, we are establishing a
strong dependency with the Jinja renderer.

In opposition to the _put the code in file_roots and the data in
pillars_ approach, there is the _pillar as a store for a set of
key-values_ approach. A full-blown configuration file abstracted in
pillar and jinja is complicated to develop, understand and maintain. I
think a better and simpler approach is to keep a configuration file
templated using just a basic (non-extensive but extensible) set of
pillar values.

== On the reusability of SaltStack state files

There is a brilliant initiative of the SaltStack community called
https://github.com/saltstack-formulas[salt-formulas]. Their goal is to
provide state files, pillar examples and configuration templates ready
to be used for provisioning. I am a contributor for two small ones:
https://github.com/saltstack-formulas/zabbix-formula[zabbix-formula] and
https://github.com/saltstack-formulas/varnish-formula[varnish-formula].

The
http://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html[design
guidelines] for formulas are clear in many aspects and it is a
recommended reading for anyone willing to write state files, even
non-formulaic ones.

In the next section, I am going to describe my proposal to extend
further the reusability of formulas, suggesting some patterns of usage.

== The Template Override and Files Switch (TOFS) pattern

I understand a formula as a *complete, independent set of SaltStack
state and configuration template files sufficient to configure a
system*. A system could be something as simple as an NTP server or some
other much more complex service that requires many state and
configuration template files.

The customization of a formula should be done mainly by providing pillar
data used later to render either the state or the configuration template
files.

=== Example: NTP before applying TOFS

Let's work with the NTP example. A basic formula that follows the
http://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html[design
guidelines] has the following files and directories tree:

.Directory and file tree for NTP
[source%nowrap, bash]
----
/srv/saltstack/salt-formulas/ntp-saltstack-formula/
  ntp/
    map.jinja
    init.sls
    conf.sls
    files/
      default/
        etc/
          ntp.conf.jinja
----

In order to use it, let's assume a
http://docs.saltstack.com/en/latest/topics/tutorials/quickstart.html[masterless
configuration]:

.`/etc/salt/minion`
[source%nowrap, yaml]
----
pillar_roots:
  base:
    - /srv/saltstack/pillar
file_client: local
file_roots:
  base:
    - /srv/saltstack/salt
    - /srv/saltstack/salt-formulas/ntp-saltstack-formula
----

.`/srv/saltstack/salt-formulas/ntp-saltstack-formula/ntp/map.jinja`
[source%nowrap, django]
----
{%- set ntp = salt['grains.filter_by']({
  'default': {
    'pkg': 'ntp',
    'service': 'ntp',
    'config': '/etc/ntp.conf',
  },
}, merge=salt['pillar.get']('ntp:lookup')) %}
----

In `init.sls` we have the minimal states required to have NTP
configured. In many cases `init.sls` is almost equivalent to an
`apt-get install` or a `yum install` of the package.

.`/srv/saltstack/salt-formulas/ntp-saltstack-formula/ntp/init.sls`
[source%nowrap, yaml]
----
{%- from 'ntp/map.jinja' import ntp with context %}

Install NTP:
  pkg.installed:
    - name: {{ ntp.pkg }}

Enable and start NTP:
  service.running:
    - name: {{ ntp.service }}
    - enabled: True
    - require:
      - pkg: Install NTP package
----

In `conf.sls` we have the configuration states. In most cases, that is
just managing configuration file templates and making them to be watched
by the service.

.`/srv/saltstack/salt-formulas/ntp-saltstack-formula/ntp/conf.sls`
[source%nowrap, yaml]
----
include:
  - ntp

{%- from 'ntp/map.jinja' import ntp with context %}

Configure NTP:
  file.managed:
    - name: {{ ntp.config }}
    - template: jinja
    - source: salt://ntp/files/default/etc/ntp.conf.jinja
    - watch_in:
      - service: Enable and start NTP service
    - require:
      - pkg: Install NTP package
----

Under `files/default`, there is a structure that mimics the one in the
minion in order to avoid clashes and confusion on where to put the
needed templates. There you can find a mostly standard template for the
configuration file.

.`/srv/saltstack/salt-formulas/ntp-saltstack-formula/ntp/files/default/etc/ntp.conf.jinja`
[source%nowrap, django]
----
{#- Managed by saltstack #}
{#- Edit pillars or override this template in saltstack if you need customization #}
{%- set settings = salt['pillar.get']('ntp', {}) %}
{%- set default_servers = ['0.ubuntu.pool.ntp.org',
                          '1.ubuntu.pool.ntp.org',
                          '2.ubuntu.pool.ntp.org',
                          '3.ubuntu.pool.ntp.org'] %}

driftfile /var/lib/ntp/ntp.drift
statistics loopstats peerstats clockstats
filegen loopstats file loopstats type day enable
filegen peerstats file peerstats type day enable
filegen clockstats file clockstats type day enable

{%- for server in settings.get('servers', default_servers) %}
server {{ server }}
{%- endfor %}

restrict -4 default kod notrap nomodify nopeer noquery
restrict -6 default kod notrap nomodify nopeer noquery

restrict 127.0.0.1
restrict ::1
----

With all this, it is easy to install and configure a simple NTP server
by just running `salt-call state.sls ntp.conf`: the package will be
installed, the service will be running and the configuration should be
correct for most of cases, even without pillar data.

Alternatively, you can define a highstate in `top.sls`
and run `salt-call state.highstate`.

.`/srv/saltstack/salt/top.sls`
[source%nowrap, yaml]
----
base:
  '*':
    - ntp.conf
----

*Customizing the formula just with pillar data*, we have the option to
define the NTP servers.

.`/srv/saltstack/pillar/top.sls`
[source%nowrap, yaml]
----
base:
  '*':
    - ntp
----

.`/srv/saltstack/pillar/ntp.sls`
[source%nowrap, yaml]
----
ntp:
  servers:
    - 0.ch.pool.ntp.org
    - 1.ch.pool.ntp.org
    - 2.ch.pool.ntp.org
    - 3.ch.pool.ntp.org
----

=== Template Override

If the customization based on pillar data is not enough, we can override
the template by creating a new one.

.`/srv/saltstack/salt/ntp/files/default/etc/ntp.conf.jinja`
[source%nowrap, django]
----
{#- Managed by saltstack #}
{#- Edit pillars or override this template in saltstack if you need customization #}

{#- Some bizarre configurations here #}
{#- ... #}

{%- for server in settings.get('servers', default_servers) %}
server {{ server }}
{%- endfor %}
----

This way we are locally *overriding the template files* offered by the
formula in order to make a more complex adaptation. Of course, this
could be applied as well to any of the files, including the state files.

=== Files Switch

To bring some order into the set of template files included in a
formula, as we commented, we suggest having a similar structure to a
normal final file system under `files/default`.

We can make different templates coexist for different minions,
classified by any
http://docs.saltstack.com/en/latest/topics/targeting/grains.html[grain]
value, by simply creating new directories under `files`. This mechanism
is based on *using values of some grains as a switch for the directories
under `files/`*.

If we decide that we want `os_family` as switch, then we could provide
the formula template variants for both the `RedHat` and `Debian`
families.

.Directory and file tree for the `files` sub-directory
[source%nowrap, bash]
----
/srv/saltstack/salt-formulas/ntp-saltstack-formula/ntp/files/
  default/
    etc/
      ntp.conf.jinja
  RedHat/
    etc/
      ntp.conf.jinja
  Debian/
    etc/
      ntp.conf.jinja
----

To make this work we need a `conf.sls` state file that takes a list of
possible files as the configuration template.

.`/srv/saltstack/salt-formulas/ntp-saltstack-formula/ntp/conf.sls`
[source%nowrap, yaml]
----
include:
  - ntp

{%- from 'ntp/map.jinja' import ntp with context %}

Configure NTP:
  file.managed:
    - name: {{ ntp.config }}
    - template: jinja
    - source:
      - salt://ntp/files/{{ grains.get('os_family', 'default') }}/etc/ntp.conf.jinja
      - salt://ntp/files/default/etc/ntp.conf.jinja
    - watch_in:
      - service: Enable and start NTP service
    - require:
      - pkg: Install NTP package
----

If we want to cover the possibility of a special template for a minion
identified by `node01` then we could have a specific template.

.`/srv/saltstack/salt/ntp/files/node01/etc/ntp.conf.jinja`
[source%nowrap, django]
----
{#- Managed by saltstack #}
{#- Edit pillars or override this template in saltstack if you need customization #}

{#- Some crazy configurations here for node01 #}
{#- ... #}
----

To make this work we could write a specially crafted `conf.sls`.

.`/srv/saltstack/salt-formulas/ntp-saltstack-formula/ntp/conf.sls`
[source%nowrap, yaml]
----
include:
  - ntp

{%- from 'ntp/map.jinja' import ntp with context %}

Configure NTP:
  file.managed:
    - name: {{ ntp.config }}
    - template: jinja
    - source:
      - salt://ntp/files/{{ grains.get('id') }}/etc/ntp.conf.jinja
      - salt://ntp/files/{{ grains.get('os_family') }}/etc/ntp.conf.jinja
      - salt://ntp/files/default/etc/ntp.conf.jinja
    - watch_in:
      - service: Enable and start NTP service
    - require:
      - pkg: Install NTP package
----

=== Using the `files_switch` macro

We can simplify the `conf.sls` with the new `files_switch` macro to use
in the `source` parameter for the `file.managed` state.

.`/srv/saltstack/salt-formulas/ntp-saltstack-formula/ntp/conf.sls`
[source%nowrap, yaml]
----
include:
  - ntp

{%- set tplroot = tpldir.split('/')[0] %}
{%- from 'ntp/map.jinja' import ntp with context %}
{%- from 'ntp/macros.jinja' import files_switch %}

Configure NTP:
  file.managed:
    - name: {{ ntp.config }}
    - template: jinja
    - source: {{ files_switch(
                  salt['config.get'](
                      tplroot ~ ':tofs:files:Configure NTP',
                      ['/etc/ntp.conf.jinja']
                  )
            ) }}
    - watch_in:
      - service: Enable and start NTP service
    - require:
      - pkg: Install NTP package
----

* This uses `config.get`, searching for `nfs:tofs:files:Configure NTP`
to determine the list of template files to use.
* If this does not yield any results, the default of
`['/etc/ntp.conf.jinja']` will be used.

In `macros.jinja`, we define this new macro `files_switch`.

.`/srv/saltstack/salt-formulas/ntp-saltstack-formula/ntp/macros.jinja`
[source%nowrap, django]
----
include::ROOT:example$macros.jinja[]
----

=== How to customise the `source` further

.Scenario for the examples below
[TIP]
====
The examples below are based on an `Ubuntu` minion called `theminion`
being configured via. pillar.
====

Using the default settings of the `files_switch` macro above, the
`source` will be:

.`source` (default)
[source%nowrap, yaml]
----
    - source:
      - salt://ntp/files/theminion/etc/ntp.conf.jinja
      - salt://ntp/files/Debian/etc/ntp.conf.jinja
      - salt://ntp/files/default/etc/ntp.conf.jinja
----

==== Customise `files`

The `files` portion can be customised:

.Customise `files`
[source%nowrap, yaml]
----
ntp:
  tofs:
    dirs:
      files: files_alt
----

Resulting in:

.`source` with `files` customised
[source%nowrap, yaml]
----
    - source:
      - salt://ntp/files_alt/theminion/etc/ntp.conf.jinja
      - salt://ntp/files_alt/Debian/etc/ntp.conf.jinja
      - salt://ntp/files_alt/default/etc/ntp.conf.jinja
----

==== Customise the use of grains

Grains can be customised and even arbitrary paths can be supplied:

.Customise `grains`
[source%nowrap, yaml]
----
ntp:
  tofs:
    files_switch:
      - any/path/can/be/used/here
      - id
      - os
      - os_family
----

Resulting in:

.`source` with `grains` customised
[source%nowrap, yaml]
----
    - source:
      - salt://ntp/files/any/path/can/be/used/here/etc/ntp.conf.jinja
      - salt://ntp/files/theminion/etc/ntp.conf.jinja
      - salt://ntp/files/Ubuntu/etc/ntp.conf.jinja
      - salt://ntp/files/Debian/etc/ntp.conf.jinja
      - salt://ntp/files/default/etc/ntp.conf.jinja
----

==== Customise the `default` path

The `default` portion of the path can be customised:

.Customise `default` directory
[source%nowrap, yaml]
----
ntp:
  tofs:
    dirs:
      default: default_alt
----

Resulting in:

.`source` with `default` directory customised
[source%nowrap, yaml]
----
    - source:
      ...
      - salt://ntp/files/default_alt/etc/ntp.conf.jinja
----

==== Customise the list of template `files`

The list of template `files` can be given:

.Customise template `files`
[source%nowrap, yaml]
----
ntp:
  tofs:
    files:
      Configure NTP:
        - '/etc/ntp.conf.jinja'
        - '/etc/ntp.conf_alt.jinja'
----

Resulting in:

.`source` with template `files` customised
[source%nowrap, yaml]
----
    - source:
      - salt://ntp/files/theminion/etc/ntp.conf.jinja
      - salt://ntp/files/theminion/etc/ntp.conf_alt.jinja
      - salt://ntp/files/Debian/etc/ntp.conf.jinja
      - salt://ntp/files/Debian/etc/ntp.conf_alt.jinja
      - salt://ntp/files/default/etc/ntp.conf.jinja
      - salt://ntp/files/default/etc/ntp.conf_alt.jinja
----
