sudo: required
cache: bundler
language: ruby

services:
  - docker

before_install:
  - bundle install

env:
  matrix:
    - INSTANCE: default-debian-9
    - INSTANCE: default-ubuntu-1804
    - INSTANCE: default-centos-7

script:
  - bundle exec kitchen verify ${INSTANCE}

before_deploy:
  # Only deploy if the build passed successfully
  - test $TRAVIS_TEST_RESULT = 0

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      # Only run if this is the `master` branch
      if: branch = master
      language: generic
      script:
        - npm install @semantic-release/changelog@3 -D
        - npm install @semantic-release/exec@3 -D
        - npm install @semantic-release/git@7 -D
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release@15

