= Changelog

:sectnums!:

== link:++https://github.com/saltstack-formulas/template-formula/compare/v5.0.1...v5.0.2++[5.0.2^] (2021-04-14)

=== Bug Fixes

* *convert-formula.sh:* replace instances of `template-formula` for CI
(https://github.com/saltstack-formulas/template-formula/commit/537fe65d456741e64823af33865f34457e0e3853[537fe65^]),
closes
https://github.com/saltstack-formulas/template-formula/issues/231[#231^]

=== Tests

* standardise use of `share` suite & `_mapdata` state [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/bbe1c7840990790eb2df564e96cc9b465093eb62[bbe1c78^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v5.0.0...v5.0.1++[5.0.1^] (2021-03-09)

=== Bug Fixes

* *convert-formula:* `_mapdata` control name must use the formula one
(https://github.com/saltstack-formulas/template-formula/commit/1f3600d66fd710bd1a41cb937cb345369d0e3e18[1f3600d^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v4.3.8...v5.0.0++[5.0.0^] (2021-03-09)

=== Bug Fixes

* *inspec:* validate `map.jinja` configuration
(https://github.com/saltstack-formulas/template-formula/commit/41d222e30c0da10fabeea23a7ab2886f02ea6479[41d222e^])

=== Continuous Integration

* *kitchen+ci:* use latest pre-salted images (after CVE) [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/6453145da16ab73c7307d14a5b864a91a5573c68[6453145^])

=== Features

* *map:* update to v5 `map.jinja`
(https://github.com/saltstack-formulas/template-formula/commit/42e19322c9c4d91a6cfa1e406723b5a799f33f80[42e1932^])

=== BREAKING CHANGES

* *map:* `map.jinja` now exports a generic `mapdata` variable
* *map:* The per grain parameter values are now under
`TEMPLATE/parameters/`

== link:++https://github.com/saltstack-formulas/template-formula/compare/v4.3.7...v4.3.8++[4.3.8^] (2021-02-21)

=== Continuous Integration

* *gemfile+lock:* use `ssf` customised `kitchen-docker` repo [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/23c2bb2dc26f4c1600d484312a79dd0af0e232d7[23c2bb2^])
* *kitchen+gitlab-ci:* use latest pre-salted images [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/00823a2d276648d184c92308f7829d0fdeefe0ba[00823a2^])

=== Tests

* *_mapdata:* add verification files for Fedora 33 & Tumbleweed
(https://github.com/saltstack-formulas/template-formula/commit/3347b85c928cebe8b0c376eae654e67e01730260[3347b85^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v4.3.6...v4.3.7++[4.3.7^] (2021-02-11)

=== Continuous Integration

* *pre-commit:* update hook for `rubocop` [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/978a7e7cd04c00fe6e7b5d113926683a86534094[978a7e7^])

=== Styles

* *inspec:* match current practices for file and control names
(https://github.com/saltstack-formulas/template-formula/commit/aa8a58b715fec48b256ff0aa8a0b697b1ae20399[aa8a58b^])

=== Tests

* *share:* standardise with latest changes [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/dab2f34c587ea6194351c768e9ba141744536607[dab2f34^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v4.3.5...v4.3.6++[4.3.6^] (2021-01-14)

=== Bug Fixes

* *_mapdata:* ensure map data is directly under `values`
(https://github.com/saltstack-formulas/template-formula/commit/bcb8e29b687f9804a1cfbda1253da290432cd5b0[bcb8e29^])

=== Tests

* *_mapdata:* update for `_mapdata/init.sls` change
(https://github.com/saltstack-formulas/template-formula/commit/50162adad7119285a649321b5f66710974a7983d[50162ad^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v4.3.4...v4.3.5++[4.3.5^] (2020-12-23)

=== Code Refactoring

* *map:* use top-level `values:` key in `map.jinja` dumps
(https://github.com/saltstack-formulas/template-formula/commit/f8e8fcb29e77d1afded74a2c92789ac8807a4768[f8e8fcb^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v4.3.3...v4.3.4++[4.3.4^] (2020-12-22)

=== Continuous Integration

* *commitlint:* ensure `upstream/master` uses main repo URL [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/e476d5a567d90592ea32f193d2264de59d261711[e476d5a^])
* *gitlab-ci:* add `rubocop` linter (with `allow_failure`) [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/4c300d01cb909f2fbed07d39b22c06198c304cdf[4c300d0^])

=== Tests

* *_mapdata:* fix existing verification files
(https://github.com/saltstack-formulas/template-formula/commit/6bbafedd1f9ad6e6b659ab6ab4b1736b5c4d9a66[6bbafed^])
* *map:* standardise `map.jinja` verification
(https://github.com/saltstack-formulas/template-formula/commit/4c8cf32db1824fb9841996d758d19c563f5414c5[4c8cf32^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v4.3.2...v4.3.3++[4.3.3^] (2020-12-16)

=== Bug Fixes

* *codeowners:* ensure `lib*` files are owned by `ssf`
(https://github.com/saltstack-formulas/template-formula/commit/d60cc1536637831ef76b2f2c84086b3f88f2684f[d60cc15^])

=== Continuous Integration

* *gitlab-ci:* use GitLab CI as Travis CI replacement
(https://github.com/saltstack-formulas/template-formula/commit/0403f62c7780a8a449617003c5363118a8b6ecd6[0403f62^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v4.3.1...v4.3.2++[4.3.2^] (2020-10-31)

=== Bug Fixes

* *convert-formula.sh:* add -_ to allowed chars in formula name
(https://github.com/saltstack-formulas/template-formula/commit/a999fee2145d9b0484049808c3c331943580cc3f[a999fee^])
* *convert-formula.sh:* delete all existing tags
(https://github.com/saltstack-formulas/template-formula/commit/7c33601fd455df90b1082791cdd282a507334898[7c33601^]),
closes
https://github.com/saltstack-formulas/template-formula/issues/210[#210^]

== link:++https://github.com/saltstack-formulas/template-formula/compare/v4.3.0...v4.3.1++[4.3.1^] (2020-10-28)

=== Tests

* *inspec:* `system.rb` must call parent class initialisation
(https://github.com/saltstack-formulas/template-formula/commit/1ff9ab15f23ba9f3b78a1b8f9dcef7a062e2b192[1ff9ab1^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v4.2.2...v4.3.0++[4.3.0^] (2020-10-12)

=== Continuous Integration

* *pre-commit:* finalise `rstcheck` configuration [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/e78aa0cb784752ae699196c6309fe93bf223a306[e78aa0c^])

=== Features

* add Gentoo support
(https://github.com/saltstack-formulas/template-formula/commit/4c2f4ede0223e83e1958be33288fa6b83cce7140[4c2f4ed^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v4.2.1...v4.2.2++[4.2.2^] (2020-10-06)

=== Bug Fixes

* *commitlint:* fix header length at 72 chars as agreed
(https://github.com/saltstack-formulas/template-formula/commit/a95061ddd088210c5111490234bc1588002cddd5[a95061d^])

=== Continuous Integration

* *pre-commit:* add to formula [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/fd89d62ec656dc3e6f84b9834860bf51359452f5[fd89d62^])
* *pre-commit:* enable/disable `rstcheck` as relevant [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/219e6b71c85f06657564c87ba58877cfc5ebe511[219e6b7^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v4.2.0...v4.2.1++[4.2.1^] (2020-09-21)

=== Continuous Integration

* *kitchen+travis:* use `tiamat` pre-salted images
(https://github.com/saltstack-formulas/template-formula/commit/3a63304f13d717fc28efbb06252ffde421ab3621[3a63304^])

=== Tests

* *oracle:* add InSpec configuration for `oraclelinux`
(https://github.com/saltstack-formulas/template-formula/commit/c4b66d8f0b5666261b43ee923565cc516b7fb92f[c4b66d8^])
* *share:* remove unnecessary hostname mangling
(https://github.com/saltstack-formulas/template-formula/commit/194aa97dff47acd59076865489914b4148b1b76d[194aa97^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v4.1.1...v4.2.0++[4.2.0^] (2020-09-04)

=== Continuous Integration

* *kitchen:* execute `_madata` state
(https://github.com/saltstack-formulas/template-formula/commit/31e1096adda4c23f77b797f35c465ba09043b3a6[31e1096^])
* *kitchen+travis:* fix `centos6` suite and rename to `upstart`
(https://github.com/saltstack-formulas/template-formula/commit/97309c6f4d6b18723ec5492564b1344155960ae0[97309c6^])

=== Features

* *map:* generate a YAML file to validate `map.jinja`
(https://github.com/saltstack-formulas/template-formula/commit/fc90075dd94d874eb283d96259f552812d8a8d82[fc90075^])

=== Tests

* *inspec:* share library to access some minion informations
(https://github.com/saltstack-formulas/template-formula/commit/64c2b6cdae1ad91959b5c0fe67863a529a070428[64c2b6c^])
* *inspec:* verify `map.jinja` dump
(https://github.com/saltstack-formulas/template-formula/commit/3dc28bfb3453079deca899352ecdff30daeb42f5[3dc28bf^])
* *platform_finger:* extract from shared library
(https://github.com/saltstack-formulas/template-formula/commit/d68ed45109aa1274c6bf236db30758d795a3ba2a[d68ed45^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v4.1.0...v4.1.1++[4.1.1^] (2020-07-28)

=== Continuous Integration

* *kitchen:* use `saltimages` Docker Hub where available [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/eab21c39fb180d3cf3be93a4ae0678b1fbe6357d[eab21c3^])
* *kitchen+travis:* add new platforms [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/111a20b47d89d275ce4ff5213656d6828acb2760[111a20b^])
* *kitchen+travis:* adjust matrix to add `3000.3` [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/19ae82632ece95047b535390bd2325fb30a09af7[19ae826^])
* *travis:* add notifications => zulip [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/ac93ad82f143ce9348f841a263df87d717034103[ac93ad8^])
* *travis:* run linters using `pre-commit`
(https://github.com/saltstack-formulas/template-formula/commit/6da26cca6a3b3ac89137d81b837633358c534396[6da26cc^])

=== Documentation

* add basic `pre-commit` usage instructions
(https://github.com/saltstack-formulas/template-formula/commit/c78c06876eb4c117b3ab00f9da479e8a4c3f1cf5[c78c068^])
* fix whitespace
(https://github.com/saltstack-formulas/template-formula/commit/d98d98f4da1096f4c60c5ec5c15d56d1945c9f50[d98d98f^])

=== Styles

* *libtofs.jinja:* use Black-inspired Jinja formatting [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/55bc69a2b194874ceb594c93c8750c320239103c[55bc69a^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v4.0.9...v4.1.0++[4.1.0^] (2020-05-12)

=== Continuous Integration

* *kitchen+travis:* adjust matrix to add `3000.2` & remove `2018.3`
 [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/efd8797e66bbe45d58a7155283b6ef47bb3fb7a4[efd8797^])
* *kitchen+travis:* remove `master-py2-arch-base-latest` [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/d693f9dabf722946a978c64ed4fbfa03653e828c[d693f9d^])
* *workflows/commitlint:* add to repo [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/574d18fc2c9628ed142a380aaff3b4c31592bb6f[574d18f^])

=== Features

* *convert-formula.sh:* assign `@NONE` as whole-formula owner
(https://github.com/saltstack-formulas/template-formula/commit/cceffffef5924b6c156890562e6f64f4872d6867[cceffff^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v4.0.8...v4.0.9++[4.0.9^] (2020-04-25)

=== Continuous Integration

* *gemfile.lock:* add to repo with updated `Gemfile` [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/d79892867549e13737a2d0f887a1388ec45704af[d798928^])

=== Documentation

* *readme:* show only one level in table of contents
(https://github.com/saltstack-formulas/template-formula/commit/446b81595822a54792cfbaf23fade20e652d7062[446b815^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v4.0.7...v4.0.8++[4.0.8^] (2020-04-19)

=== Bug Fixes

* *libsaltcli:* update `salt-ssh` detection for `enable_ssh_minions`
(https://github.com/saltstack-formulas/template-formula/commit/f0e7192fb5a546cb0569f9d4257807c8592a00b6[f0e7192^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v4.0.6...v4.0.7++[4.0.7^] (2020-04-15)

=== Bug Fixes

* *convert-formula.sh:* use portable sed function to make replacements
(https://github.com/saltstack-formulas/template-formula/commit/41e10b5249e0c8827844f438d1995cf7cb42d63a[41e10b5^]),
closes
https://github.com/saltstack-formulas/template-formula/issues/192[#192^]

=== Continuous Integration

* *travis:* add quick check that `convert-formula.sh` has worked
(https://github.com/saltstack-formulas/template-formula/commit/83120632f3a2246ac640155d374634836c34965a[8312063^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v4.0.5...v4.0.6++[4.0.6^] (2020-04-07)

=== Bug Fixes

* *running.sls:* use `watch` not `require` to ensure service restart
(https://github.com/saltstack-formulas/template-formula/commit/3a1fc35a13f66714cd42583f13679c6f189ae48f[3a1fc35^])

=== Code Refactoring

* *libsaltcli:* use the `opts` dict throughout [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/69b632fbe613d4f99a48f59f64ec93c3897431c8[69b632f^])

=== Continuous Integration

* *kitchen+travis:* adjust matrix to add `3000` & remove `2017.7` [skip
ci]
(https://github.com/saltstack-formulas/template-formula/commit/f81c372dfe12d42139275fc8c9e7aad1b6eec976[f81c372^])
* *kitchen+travis:* adjust matrix to update `3000` to `3000.1` [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/f48a7275644d2baef06adb0d8e74b3c19fd2d8a0[f48a727^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v4.0.4...v4.0.5++[4.0.5^] (2020-03-23)

=== Bug Fixes

* *libtofs:* “files_switch” mess up the variable exported by “map.jinja”
 [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/241646fe96447369df00f17ec1c27a53de08bec4[241646f^])

=== Code Refactoring

* *service:* use `systemd-journald` instead of `systemd-udevd`
(https://github.com/saltstack-formulas/template-formula/commit/a2651058be0d8b09f910aeee2f23703b6cefaa09[a265105^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v4.0.3...v4.0.4++[4.0.4^] (2020-02-14)

=== Bug Fixes

* *libtofs:* “files_switch” mess up the variable defined by “map.jinja”
(https://github.com/saltstack-formulas/template-formula/commit/ab4ce751a4640303af7acbf7a278aef79b530bb6[ab4ce75^])

=== Continuous Integration

* *kitchen:* avoid using bootstrap for `master` instances
(https://github.com/saltstack-formulas/template-formula/commit/6ecdb99f83b807b4679dc6534ae425b97eefbe54[6ecdb99^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v4.0.2...v4.0.3++[4.0.3^] (2020-01-27)

=== Bug Fixes

* fix `CentOS Linux-7` and add `os` details from current CI setup
(https://github.com/saltstack-formulas/template-formula/commit/4be16ca4befeddeeb8be1199cd088df7c547523f[4be16ca^])
* *travis:* reinstate conversion test [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/5d47fda1b9f52bff1a4c2cad5097cd3d8cd43521[5d47fda^])

=== Continuous Integration

* *travis:* use `major.minor` for `semantic-release` version [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/e9bfb71fdc0fa80ac63e6ce724f0e5621a4b30ca[e9bfb71^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v4.0.1...v4.0.2++[4.0.2^] (2019-12-19)

=== Bug Fixes

* *convert-formula.sh:* remove "Using this template" post-conversion
(https://github.com/saltstack-formulas/template-formula/commit/55ab937c047374fce0548d8c18e8513bc15ead78[55ab937^])
* *convert-formula.sh:* remove `rubocop` override post-conversion
(https://github.com/saltstack-formulas/template-formula/commit/aca4e4428964da745e7b1b7dce15d2c751f76490[aca4e44^])
* *convert-formula.sh:* remove CI test post-conversion
(https://github.com/saltstack-formulas/template-formula/commit/06ec949fd17bb4b52bb230a6ad2eddfe08a4e693[06ec949^])
* *convert-formula.sh:* reset version to `1.0.0`
(https://github.com/saltstack-formulas/template-formula/commit/39889ce303cb57125ba0411ab55266ee018d40e1[39889ce^])

=== Documentation

* *convert-formula.sh:* add usage guide
(https://github.com/saltstack-formulas/template-formula/commit/539a335f8b01ffb3944b742cc2f5852a718546dd[539a335^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v4.0.0...v4.0.1++[4.0.1^] (2019-12-17)

=== Bug Fixes

* *convert-formula.sh:* apply remaining suggestions from
https://github.com/saltstack-formulas/template-formula/issues/180[#180^]
(https://github.com/saltstack-formulas/template-formula/commit/76ecd447be66fd9b33ace56836796d3ce24537db[76ecd44^]),
closes
https://github.com//github.com/saltstack-formulas/template-formula/pull/180/issues/discussion_r357308821[/github.com/saltstack-formulas/template-formula/pull/180#discussion_r357308821^]
https://github.com//github.com/saltstack-formulas/template-formula/pull/180/issues/discussion_r357318860[/github.com/saltstack-formulas/template-formula/pull/180#discussion_r357318860^]
https://github.com//github.com/saltstack-formulas/template-formula/pull/180/issues/discussion_r357362707[/github.com/saltstack-formulas/template-formula/pull/180#discussion_r357362707^]

== link:++https://github.com/saltstack-formulas/template-formula/compare/v3.3.4...v4.0.0++[4.0.0^] (2019-12-16)

=== Code Refactoring

* improve reusability using an unique keyword TEMPLATE
(https://github.com/saltstack-formulas/template-formula/commit/2e8ded6565f7bad166323792bf42979aac2980fa[2e8ded6^])

=== Continuous Integration

* *gemfile:* restrict `train` gem version until upstream fix [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/1b6164fc4a5bda44e8cb1104039606603dab4c2e[1b6164f^])
* *travis:* quote pathspecs used with `git ls-files` [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/341f495336da0e35d92b3b4acda30f9efa44ec52[341f495^])

=== Features

* add script to ease conversion from template to real formula
(https://github.com/saltstack-formulas/template-formula/commit/edfa269e9655407ca26788a8d5564c759abbbb30[edfa269^])

=== Tests

* add CI test of conversion script
(https://github.com/saltstack-formulas/template-formula/commit/7ad85ae0db21888921efabbc88bcafbc65e5bd21[7ad85ae^])

=== BREAKING CHANGES

* changed all state names and ids

== link:++https://github.com/saltstack-formulas/template-formula/compare/v3.3.3...v3.3.4++[3.3.4^] (2019-11-27)

=== Bug Fixes

* *release.config.js:* use full commit hash in commit link [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/4ac8d92778977ed63fe99e4506a2b0a2d41a2bce[4ac8d92^])

=== Continuous Integration

* *kitchen:* use `debian-10-master-py3` instead of `develop` [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/14ebf928bc07cefa086523e63bed5df7c2879e9b[14ebf92^])
* *kitchen:* use `develop` image until `master` is ready (`amazonlinux`)
 [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/42482d7f9b77f5d34417e25233a9f385075feace[42482d7^])
* *kitchen+travis:* upgrade matrix after `2019.2.2` release [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/d0e07b88834f68cc81ce4de34c14a880347fc497[d0e07b8^])
* *travis:* apply changes from build config validation [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/b625245fc62deb6da7cb35de1280ec267718b1cd[b625245^])
* *travis:* opt-in to `dpl v2` to complete build config validation [skip
ci]
(https://github.com/saltstack-formulas/template-formula/commit/f1fbf7f620c886827c70fb3970e3b2fac58b8db8[f1fbf7f^])
* *travis:* run `shellcheck` during lint job
(https://github.com/saltstack-formulas/template-formula/commit/a7116654d875ecb0e7e3e10fc96cbab2e91575f7[a711665^])
* *travis:* update `salt-lint` config for `v0.0.10` [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/faea464f923f552e23a83f28e3192c437f7eabfe[faea464^])
* *travis:* use build config validation (beta) [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/66494bbc1058adc9ed6fa0074b1c4b6018c4cd48[66494bb^])

=== Performance Improvements

* *travis:* improve `salt-lint` invocation [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/7a96cd77db71eb8b022df7bd5c1014664124a022[7a96cd7^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v3.3.2...v3.3.3++[3.3.3^] (2019-10-16)

=== Documentation

* *contributing:* add recent `semantic-release` formulas [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/e6fb519[e6fb519^])
* *contributing:* remove to use org-level file instead [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/d2ebccf[d2ebccf^])
* *readme:* update link to `CONTRIBUTING` [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/ed61d09[ed61d09^])
* *reamde:* have special notes section
(https://github.com/saltstack-formulas/template-formula/commit/c68aed5[c68aed5^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v3.3.1...v3.3.2++[3.3.2^] (2019-10-08)

=== Bug Fixes

* *rubocop:* add fixes using `rubocop --safe-auto-correct`
(https://github.com/saltstack-formulas/template-formula/commit/484ce24[484ce24^])
* *rubocop:* fix remaining errors manually
(https://github.com/saltstack-formulas/template-formula/commit/9566b6f[9566b6f^])

=== Code Refactoring

* *travis:* merge `lint` stage into the `test` stage
(https://github.com/saltstack-formulas/template-formula/commit/d3b93f8[d3b93f8^])

=== Continuous Integration

* *kitchen:* install required packages to bootstrapped `opensuse` [skip
ci]
(https://github.com/saltstack-formulas/template-formula/commit/1cfed60[1cfed60^])
* *kitchen:* use bootstrapped `opensuse` images until `2019.2.2` [skip
ci]
(https://github.com/saltstack-formulas/template-formula/commit/0467bdf[0467bdf^])
* *travis:* quote `$\{INSTANCE}` when running `kitchen verify`
(https://github.com/saltstack-formulas/template-formula/commit/00d56a4[00d56a4^]),
closes
https://github.com//github.com/saltstack-formulas/template-formula/pull/175/issues/discussion_r332525964[/github.com/saltstack-formulas/template-formula/pull/175#discussion_r332525964^]
* *travis:* run `rubocop` during the `Lint` job
(https://github.com/saltstack-formulas/template-formula/commit/8d8c766[8d8c766^])
* *travis:* run `salt-lint` during the `Lint` job
(https://github.com/saltstack-formulas/template-formula/commit/2df4646[2df4646^]),
closes
https://github.com//freenode.logbot.info/saltstack-formulas/20191004/issues/c2723464[/freenode.logbot.info/saltstack-formulas/20191004#c2723464^]
https://github.com//freenode.logbot.info/saltstack-formulas/20191004/issues/c2724272[/freenode.logbot.info/saltstack-formulas/20191004#c2724272^]
* *travis:* use `env` and `name` for improved display in Travis
(https://github.com/saltstack-formulas/template-formula/commit/5f773d1[5f773d1^]),
closes
https://github.com//github.com/saltstack-formulas/template-formula/pull/175/issues/discussion_r332613933[/github.com/saltstack-formulas/template-formula/pull/175#discussion_r332613933^]

=== Documentation

* *bug_report:* add section requesting commit hash / release tag
(https://github.com/saltstack-formulas/template-formula/commit/faccb6a[faccb6a^])
* *bug_report:* group into sections for better logical ordering
(https://github.com/saltstack-formulas/template-formula/commit/e9b6c2f[e9b6c2f^])
* *contributing:* add recent `semantic-release` formula
(https://github.com/saltstack-formulas/template-formula/commit/c2924b0[c2924b0^])
* *contributing:* add recent `semantic-release` formula
(https://github.com/saltstack-formulas/template-formula/commit/8d2318c[8d2318c^])
* *contributing:* add recent `semantic-release` formula [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/85118de[85118de^])
* *issues:* provide `Bug report` & `Feature request` templates
(https://github.com/saltstack-formulas/template-formula/commit/f90f1f6[f90f1f6^])
* *issues:* use `Meta` instead of `Optional` as suggested
(https://github.com/saltstack-formulas/template-formula/commit/65cadb4[65cadb4^]),
closes
https://github.com//github.com/saltstack-formulas/template-formula/pull/174/issues/issuecomment-538999459[/github.com/saltstack-formulas/template-formula/pull/174#issuecomment-538999459^]
* *issues:* use larger headings (from level 4 to level 3)
(https://github.com/saltstack-formulas/template-formula/commit/53e7b75[53e7b75^])
* *pillar.example:* fix TOFS comment to explain the default path [skip
ci]
(https://github.com/saltstack-formulas/template-formula/commit/fde5063[fde5063^]),
closes
https://github.com//github.com/saltstack-formulas/libvirt-formula/pull/60/issues/issuecomment-537965254[/github.com/saltstack-formulas/libvirt-formula/pull/60#issuecomment-537965254^]
https://github.com//github.com/saltstack-formulas/libvirt-formula/pull/60/issues/issuecomment-537988138[/github.com/saltstack-formulas/libvirt-formula/pull/60#issuecomment-537988138^]
* *pillar.example:* improve TOFS comment to explain the default path
 [skip ci]
(https://github.com/saltstack-formulas/template-formula/commit/27d2fe4[27d2fe4^]),
closes
https://github.com//github.com/saltstack-formulas/nginx-formula/blob/17291a0ae2c2554707b79d897bb6ddec716e8426/pillar.example/issues/L340-L341[/github.com/saltstack-formulas/nginx-formula/blob/17291a0ae2c2554707b79d897bb6ddec716e8426/pillar.example#L340-L341^]

== link:++https://github.com/saltstack-formulas/template-formula/compare/v3.3.0...v3.3.1++[3.3.1^] (2019-09-23)

=== Bug Fixes

* *subcomponent:* clean referencing wrong sls
(https://github.com/saltstack-formulas/template-formula/commit/394808e[394808e^])

=== Continuous Integration

* use `dist: bionic` & apply `opensuse-leap-15` SCP error workaround
(https://github.com/saltstack-formulas/template-formula/commit/330b0cb[330b0cb^])
* *kitchen:* change `log_level` to `debug` instead of `info`
(https://github.com/saltstack-formulas/template-formula/commit/1b929ff[1b929ff^])
* *platform:* add `arch-base-latest`
(https://github.com/saltstack-formulas/template-formula/commit/042e8e2[042e8e2^])
* *yamllint:* add rule `empty-values` & use new `yaml-files` setting
(https://github.com/saltstack-formulas/template-formula/commit/70ed7e2[70ed7e2^]),
closes
https://github.com/saltstack-formulas/template-formula/issues/164[#164^]

=== Documentation

* *contributing:* add recent `semantic-release` formulas
(https://github.com/saltstack-formulas/template-formula/commit/7f36ae9[7f36ae9^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v3.2.1...v3.3.0++[3.3.0^] (2019-08-27)

=== Bug Fixes

* *libtofs:* avoid using subpath by default
(https://github.com/saltstack-formulas/template-formula/commit/c07471d[c07471d^])

=== Code Refactoring

* *libtofs:* remove deprecated `v1_path_prefix` argument
(https://github.com/saltstack-formulas/template-formula/commit/ad2a965[ad2a965^])

=== Features

* *yamllint:* include for this repo and apply rules throughout
(https://github.com/saltstack-formulas/template-formula/commit/e76525f[e76525f^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v3.2.0...v3.2.1++[3.2.1^] (2019-08-06)

=== Code Refactoring

* *tofs:* move subcomponent definition to `defaults.yaml`
(https://github.com/saltstack-formulas/template-formula/commit/c269673[c269673^])
* *tofs:* move subcomponent templates to first `source` match
(https://github.com/saltstack-formulas/template-formula/commit/70cc92d[70cc92d^])

=== Continuous Integration

* *kitchen+travis:* replace EOL pre-salted images
(https://github.com/saltstack-formulas/template-formula/commit/42ab22c[42ab22c^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v3.1.1...v3.2.0++[3.2.0^] (2019-08-03)

=== Bug Fixes

* *formula:* update to current oldest supported version of Salt
(https://github.com/saltstack-formulas/template-formula/commit/878eca1[878eca1^])

=== Documentation

* *libtofs:* explain usage of sub-directory for components
(https://github.com/saltstack-formulas/template-formula/commit/42a75d9[42a75d9^])
* *readme:* describe the new “template.subcomponent” states
(https://github.com/saltstack-formulas/template-formula/commit/6b595cd[6b595cd^])

=== Features

* *sub-component:* manage a dedicated configuration file
(https://github.com/saltstack-formulas/template-formula/commit/c4440d7[c4440d7^])
* *tofs:* lookup files directory in “tpldir” hierarchy
(https://github.com/saltstack-formulas/template-formula/commit/5c495fb[5c495fb^])

=== Tests

* *inspec:* verify subcomponent configuration file
(https://github.com/saltstack-formulas/template-formula/commit/fd55e03[fd55e03^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v3.1.0...v3.1.1++[3.1.1^] (2019-07-25)

=== Bug Fixes

* *tofs:* prepend the config-based `source_files` to the default
(https://github.com/saltstack-formulas/template-formula/commit/3483e76[3483e76^]),
closes
https://github.com//github.com/saltstack-formulas/nginx-formula/pull/247/issues/issuecomment-514262549[/github.com/saltstack-formulas/nginx-formula/pull/247#issuecomment-514262549^]
https://github.com/saltstack-formulas/template-formula/issues/151[#151^]

=== Documentation

* *tofs:* ensure merged will all recent changes
(https://github.com/saltstack-formulas/template-formula/commit/6a614d9[6a614d9^])
* *tofs:* update from `nginx-formula`
(https://github.com/saltstack-formulas/template-formula/commit/23a221e[23a221e^]),
closes
https://github.com//github.com/saltstack-formulas/nginx-formula/pull/238/issues/discussion_r289124365[/github.com/saltstack-formulas/nginx-formula/pull/238#discussion_r289124365^]

== link:++https://github.com/saltstack-formulas/template-formula/compare/v3.0.9...v3.1.0++[3.1.0^] (2019-07-24)

=== Bug Fixes

* *grain:* fix grain value
(https://github.com/saltstack-formulas/template-formula/commit/26edfa0[26edfa0^])

=== Documentation

* *map:* update comments in `os*.yaml` after adding `osarchmap`
(https://github.com/saltstack-formulas/template-formula/commit/d71a258[d71a258^])

=== Features

* *mapping:* introduce osarchmap per issue
https://github.com/saltstack-formulas/template-formula/issues/13[#13^]
(https://github.com/saltstack-formulas/template-formula/commit/41ac40d[41ac40d^])

=== Tests

* *osarch:* add unit test for osarch
(https://github.com/saltstack-formulas/template-formula/commit/1be2052[1be2052^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v3.0.8...v3.0.9++[3.0.9^] (2019-07-24)

=== Bug Fixes

* *libtofs:* don't crash if “tofs.files_switch” lookup a list
(https://github.com/saltstack-formulas/template-formula/commit/0979d35[0979d35^])

=== Documentation

* *contributing:* add recent `semantic-release` formula
(https://github.com/saltstack-formulas/template-formula/commit/f9def86[f9def86^])
* *contributing:* add recent `semantic-release` formula
(https://github.com/saltstack-formulas/template-formula/commit/ed8c55a[ed8c55a^])
* *contributing:* add recent `semantic-release` formulas
(https://github.com/saltstack-formulas/template-formula/commit/57d0b85[57d0b85^])

=== Tests

* *libtofs:* “tofs.files_switch” lookup can return a list
(https://github.com/saltstack-formulas/template-formula/commit/13f1728[13f1728^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v3.0.7...v3.0.8++[3.0.8^] (2019-07-08)

=== Documentation

* *contributing:* add template-formula to `semantic-release` formulas
(https://github.com/saltstack-formulas/template-formula/commit/87e4ebc[87e4ebc^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v3.0.6...v3.0.7++[3.0.7^] (2019-07-04)

=== Documentation

* *contributing:* add recent `semantic-release` formula
(https://github.com/saltstack-formulas/template-formula/commit/c679cb5[c679cb5^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v3.0.5...v3.0.6++[3.0.6^] (2019-06-28)

=== Code Refactoring

* *string:* remove capitalisation from 'template' string
(https://github.com/saltstack-formulas/template-formula/commit/7062210[7062210^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v3.0.4...v3.0.5++[3.0.5^] (2019-06-28)

=== Documentation

* *contributing:* add recent `semantic-release` formula
(https://github.com/saltstack-formulas/template-formula/commit/fc50a9e[fc50a9e^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v3.0.3...v3.0.4++[3.0.4^] (2019-06-27)

=== Documentation

* *contributing:* add recent `semantic-release` formulas
(https://github.com/saltstack-formulas/template-formula/commit/22052fc[22052fc^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v3.0.2...v3.0.3++[3.0.3^] (2019-06-25)

=== Documentation

* *contributing:* add recent `semantic-release` formula
(https://github.com/saltstack-formulas/template-formula/commit/7f56237[7f56237^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v3.0.1...v3.0.2++[3.0.2^] (2019-06-20)

=== Documentation

* *contributing:* add recent `semantic-release` formulas
(https://github.com/saltstack-formulas/template-formula/commit/461c7a5[461c7a5^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v3.0.0...v3.0.1++[3.0.1^] (2019-06-16)

=== Tests

* *inspec:* readme for default profile & os-name depreciated
(https://github.com/saltstack-formulas/template-formula/commit/3fa7bce[3fa7bce^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.2.1...v3.0.0++[3.0.0^] (2019-06-13)

=== Code Refactoring

* *pkgname:* reserve 'pkg' as packaging dict
(https://github.com/saltstack-formulas/template-formula/commit/c6ae81c[c6ae81c^])

=== Continuous Integration

* *kitchen+travis:* modify matrix to include `develop` platform
(https://github.com/saltstack-formulas/template-formula/commit/7b5d4ff[7b5d4ff^])

=== BREAKING CHANGES

* *pkgname:* the parameter `pkg` is now a dictionary. References to
`template.pkg` should be changed to `template.pkg.name`.

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.2.0...v2.2.1++[2.2.1^] (2019-05-31)

=== Code Refactoring

* *``osfamilymap``:* avoid *BSD ambiguity with MacOS `rootgroup`
(https://github.com/saltstack-formulas/template-formula/commit/3338605[3338605^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.1.18...v2.2.0++[2.2.0^] (2019-05-31)

=== Features

* *macos:* basic package and group handling
(https://github.com/saltstack-formulas/template-formula/commit/8c3fe22[8c3fe22^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.1.17...v2.1.18++[2.1.18^] (2019-05-29)

=== Bug Fixes

* *``libtofs``:* use `select` to deal with empty strings in path
(https://github.com/saltstack-formulas/template-formula/commit/afe0751[afe0751^])
* *``libtofs``:* use `strip` to deal with leading/trailing slashes
(https://github.com/saltstack-formulas/template-formula/commit/2563a46[2563a46^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.1.16...v2.1.17++[2.1.17^] (2019-05-27)

=== Continuous Integration

* *kitchen:* add Bundler binstub for Kitchen
(https://github.com/saltstack-formulas/template-formula/commit/7bb7c53[7bb7c53^])

=== Documentation

* *readme:* tidy headings
(https://github.com/saltstack-formulas/template-formula/commit/d931ed1[d931ed1^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.1.15...v2.1.16++[2.1.16^] (2019-05-27)

=== Documentation

* *contributing:* add ufw formula to semantic release formulas
(https://github.com/saltstack-formulas/template-formula/commit/18ff689[18ff689^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.1.14...v2.1.15++[2.1.15^] (2019-05-25)

=== Tests

* *``services_spec``:* remove temporary `suse` conditional
(https://github.com/saltstack-formulas/template-formula/commit/00d4a77[00d4a77^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.1.13...v2.1.14++[2.1.14^] (2019-05-25)

=== Bug Fixes

* *``config/file``:* add missing space before Jinja `}}`
(https://github.com/saltstack-formulas/template-formula/commit/5cd08ab[5cd08ab^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.1.12...v2.1.13++[2.1.13^] (2019-05-24)

=== Documentation

* *readme:* add testing requirements section (from `vault-formula`)
(https://github.com/saltstack-formulas/template-formula/commit/e04413e[e04413e^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.1.11...v2.1.12++[2.1.12^] (2019-05-24)

=== Continuous Integration

* *travis:* improve recommended matrix usage comment
(https://github.com/saltstack-formulas/template-formula/commit/b08a0fd[b08a0fd^])
* *travis:* reduce matrix down to 6 instances (ref:
https://github.com/saltstack-formulas/template-formula/issues/118[#118^])
(https://github.com/saltstack-formulas/template-formula/commit/a8834e2[a8834e2^])

=== Documentation

* *contributing:* add `bind-formula` to `semantic-release` formulas
(https://github.com/saltstack-formulas/template-formula/commit/3da78b0[3da78b0^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.1.10...v2.1.11++[2.1.11^] (2019-05-18)

=== Documentation

* *contributing:* add recent `semantic-release` formula
(https://github.com/saltstack-formulas/template-formula/commit/486b393[486b393^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.1.9...v2.1.10++[2.1.10^] (2019-05-16)

=== Documentation

* *contributing:* fix link to contributing docs
(https://github.com/saltstack-formulas/template-formula/commit/b6a33d3[b6a33d3^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.1.8...v2.1.9++[2.1.9^] (2019-05-16)

=== Documentation

* move contributing sections and links to ease adaptation
(https://github.com/saltstack-formulas/template-formula/commit/741896d[741896d^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.1.7...v2.1.8++[2.1.8^] (2019-05-16)

=== Documentation

* *contributing:* add recent `semantic-release` formulas
(https://github.com/saltstack-formulas/template-formula/issues/110[#110^])
(https://github.com/saltstack-formulas/template-formula/commit/ab7afd4[ab7afd4^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.1.6...v2.1.7++[2.1.7^] (2019-05-15)

=== Styles

* *indent:* fix indentation
(https://github.com/saltstack-formulas/template-formula/commit/34d1307[34d1307^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.1.5...v2.1.6++[2.1.6^] (2019-05-15)

=== Bug Fixes

* *``map.jinja``:* _merge_ defaults and `config.get`
(https://github.com/saltstack-formulas/template-formula/commit/91bc2f0[91bc2f0^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.1.4...v2.1.5++[2.1.5^] (2019-05-15)

=== Bug Fixes

* *``map.jinja``:* use tplroot
(https://github.com/saltstack-formulas/template-formula/commit/b9c5e03[b9c5e03^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.1.3...v2.1.4++[2.1.4^] (2019-05-15)

=== Bug Fixes

* *``map.jinja``:* remove `merge` from `config.get` (for `salt-ssh`)
(https://github.com/saltstack-formulas/template-formula/commit/00e474c[00e474c^]),
closes
https://github.com/saltstack-formulas/template-formula/issues/95[#95^]

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.1.2...v2.1.3++[2.1.3^] (2019-05-13)

=== Bug Fixes

* *travis:* don't install gems twice
(https://github.com/saltstack-formulas/template-formula/commit/925d8e2[925d8e2^])

=== Documentation

* *readme:* add testing section based on `postgres-formula`
(https://github.com/saltstack-formulas/template-formula/commit/c309d5f[c309d5f^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.1.1...v2.1.2++[2.1.2^] (2019-05-13)

=== Bug Fixes

* *gitignore:* add Gemfile.lock to .gitignore
(https://github.com/saltstack-formulas/template-formula/commit/87fa410[87fa410^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.1.0...v2.1.1++[2.1.1^] (2019-05-13)

=== Documentation

* *semantic-release:* add list of semantic-release compatible formulas
(https://github.com/saltstack-formulas/template-formula/commit/97b19b9[97b19b9^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.0.6...v2.1.0++[2.1.0^] (2019-05-12)

=== Features

* *centos-6:* reshape formula and tests for this platform
(https://github.com/saltstack-formulas/template-formula/commit/a4b1608[a4b1608^]),
closes
https://github.com/saltstack-formulas/template-formula/issues/104[#104^]

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.0.5...v2.0.6++[2.0.6^] (2019-05-02)

=== Continuous Integration

* *kitchen+travis:* use latest pre-salted images
(https://github.com/saltstack-formulas/template-formula/commit/91ef13b[91ef13b^])

=== Tests

* *inspec:* disable `service`-based tests for `opensuse-leap-15`
(https://github.com/saltstack-formulas/template-formula/commit/848c2ad[848c2ad^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.0.4...v2.0.5++[2.0.5^] (2019-04-30)

=== Documentation

* *tofs:* remove whitespace from blank line
(https://github.com/saltstack-formulas/template-formula/commit/0881b7d[0881b7d^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.0.3...v2.0.4++[2.0.4^] (2019-04-27)

=== Code Refactoring

* *map:* use `config.get` instead of `pillar.get`
(https://github.com/saltstack-formulas/template-formula/commit/5dc0b86[5dc0b86^])

=== Continuous Integration

* *gemfile:* update `kitchen-salt` version
(https://github.com/saltstack-formulas/template-formula/commit/ad31c32[ad31c32^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.0.2...v2.0.3++[2.0.3^] (2019-04-24)

=== Bug Fixes

* *comments:* explain that at least an empty dict is required
(https://github.com/saltstack-formulas/template-formula/commit/426f955[426f955^]),
closes
https://github.com/saltstack-formulas/template-formula/issues/93[#93^]

=== Continuous Integration

* *kitchen:* use pre-salted images instead
(https://github.com/saltstack-formulas/template-formula/commit/2855ed6[2855ed6^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.0.1...v2.0.2++[2.0.2^] (2019-04-22)

=== Code Refactoring

* *config_clean:* remove unused import from `libtofs.jinja`
(https://github.com/saltstack-formulas/template-formula/commit/b7cb585[b7cb585^])

=== Continuous Integration

* *kitchen+travis:* implement new distro-python-salt_version matrix
(https://github.com/saltstack-formulas/template-formula/commit/bd4792d[bd4792d^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v2.0.0...v2.0.1++[2.0.1^] (2019-03-25)

=== Code Refactoring

* *tofs:* ensure (v2 > v1 > default) checking for `src_files`
(https://github.com/saltstack-formulas/template-formula/commit/3e62d7b[3e62d7b^])
* *tofs:* make `files_switch` macro fully portable
(https://github.com/saltstack-formulas/template-formula/commit/a98b777[a98b777^])
* *tofs:* use `config` rather than `pillar` throughout
(https://github.com/saltstack-formulas/template-formula/commit/5730e94[5730e94^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v1.2.6...v2.0.0++[2.0.0^] (2019-03-24)

=== Code Refactoring

* *tofs:* move “files_switch” macro to “libtofs.jinja”
(https://github.com/saltstack-formulas/template-formula/commit/da7e692[da7e692^])

=== BREAKING CHANGES

* *tofs:* every formula writer will need to change the import to use
this new version.
* template/libtofs.jinja: provides the “files_switch” macro.
* docs/TOFS_pattern.rst: update documentation to use the new path.
* template/config/clean.sls: change import from “macros.jinja” to
“libtofs.jinja”.
* template/config/file.sls: ditoo.

== link:++https://github.com/saltstack-formulas/template-formula/compare/v1.2.5...v1.2.6++[1.2.6^] (2019-03-24)

=== Reverts

* *kitchen+travis:* use `debian:jessie-backports` as `debian-8`
(https://github.com/saltstack-formulas/template-formula/commit/dcd141a[dcd141a^]),
closes
https://github.com//github.com/saltstack/salt-pack/issues/657/issues/issuecomment-474954298[/github.com/saltstack/salt-pack/issues/657#issuecomment-474954298^]

== link:++https://github.com/saltstack-formulas/template-formula/compare/v1.2.4...v1.2.5++[1.2.5^] (2019-03-23)

=== Bug Fixes

* *travis:* use version numbers in Gemfile to prevent failed builds
(https://github.com/saltstack-formulas/template-formula/commit/35f7111[35f7111^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v1.2.3...v1.2.4++[1.2.4^] (2019-03-22)

=== Code Refactoring

* *tofs:* avoid using “salt['config.get']” for formula writers
(https://github.com/saltstack-formulas/template-formula/commit/60d43e7[60d43e7^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v1.2.2...v1.2.3++[1.2.3^] (2019-03-13)

=== Documentation

* *tofs:* incorrect path for “source_files” lookup key
(https://github.com/saltstack-formulas/template-formula/commit/a76f659[a76f659^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v1.2.1...v1.2.2++[1.2.2^] (2019-03-09)

=== Bug Fixes

* *tofs:* update use of state ID in `config` and `pillar`
(https://github.com/saltstack-formulas/template-formula/commit/3d9a24c[3d9a24c^])
* *tofs:* use `source_files` instead of `files`
(https://github.com/saltstack-formulas/template-formula/commit/5110716[5110716^]),
closes
https://github.com//freenode.logbot.info/saltstack-formulas/20190308/issues/c2046753[/freenode.logbot.info/saltstack-formulas/20190308#c2046753^]

== link:++https://github.com/saltstack-formulas/template-formula/compare/v1.2.0...v1.2.1++[1.2.1^] (2019-03-07)

=== Code Refactoring

* *kitchen:* `pillars-from-files` => `pillars_from_files`
(https://github.com/saltstack-formulas/template-formula/commit/7c954a7[7c954a7^]),
closes
https://github.com//github.com/saltstack-formulas/packages-formula/pull/50/issues/discussion_r262769817[/github.com/saltstack-formulas/packages-formula/pull/50#discussion_r262769817^]

=== Styles

* *map:* use `-` for each Jinja block
(https://github.com/saltstack-formulas/template-formula/commit/64e3834[64e3834^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v1.1.2...v1.2.0++[1.2.0^] (2019-03-03)

=== Features

* *m2r:* use `m2r` to convert automatic `.md` files to `.rst`
(https://github.com/saltstack-formulas/template-formula/commit/b86ddf4[b86ddf4^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v1.1.1...v1.1.2++[1.1.2^] (2019-03-03)

=== Documentation

* *contributing:* add documentation contribution guidelines
(https://github.com/saltstack-formulas/template-formula/commit/dff0ee8[dff0ee8^])
* *rtd:* add comment to CSS file for overriding in-use Sphinx theme
(https://github.com/saltstack-formulas/template-formula/commit/f237364[f237364^])
* *rtd:* clean up numerous issues and inconsistencies
(https://github.com/saltstack-formulas/template-formula/commit/ad5a8b8[ad5a8b8^])
* *tofs:* use `literalinclude` of `macros.jinja` instead of code dupe
(https://github.com/saltstack-formulas/template-formula/commit/3f0071b[3f0071b^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v1.1.0...v1.1.1++[1.1.1^] (2019-03-01)

=== Continuous Integration

* *travis:* remove obsolete `markdown-toc` process
(https://github.com/saltstack-formulas/template-formula/commit/97fbb60[97fbb60^])

=== Documentation

* *contributing:* add TOC to match all other pages
(https://github.com/saltstack-formulas/template-formula/commit/7b1a2a9[7b1a2a9^])
* *readme:* add Read the Docs build status badge
(https://github.com/saltstack-formulas/template-formula/commit/f47797d[f47797d^])
* *tofs:* replace existing `.md` with `.rst` and add to RTD
(https://github.com/saltstack-formulas/template-formula/commit/fd68168[fd68168^])
* *tofs:* use table to list authorship
(https://github.com/saltstack-formulas/template-formula/commit/2f0e20f[2f0e20f^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v1.0.1...v1.1.0++[1.1.0^] (2019-03-01)

=== Documentation

* *rtd:* add basic `docs/conf.py` to allow additional customisation
(https://github.com/saltstack-formulas/template-formula/commit/18d3924[18d3924^])

=== Features

* *rtd:* provide custom CSS file for overriding in-use Sphinx theme
(https://github.com/saltstack-formulas/template-formula/commit/24bd338[24bd338^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v1.0.0...v1.0.1++[1.0.1^] (2019-03-01)

=== Continuous Integration

* *travis:* remove unavailable files from `markdown-toc` process
(https://github.com/saltstack-formulas/template-formula/commit/3148f0d[3148f0d^])

=== Documentation

* *contributing:* convert to `.rst` and move to `docs` subdir
(https://github.com/saltstack-formulas/template-formula/commit/474f318[474f318^])
* *index:* add `CONTRIBUTING` to the `toctree`
(https://github.com/saltstack-formulas/template-formula/commit/0c98e67[0c98e67^])
* *readme:* move under `docs` subdir to access in both GitHub and RTD
(https://github.com/saltstack-formulas/template-formula/commit/c92f674[c92f674^])
* *readme:* update heading markers for consistency
(https://github.com/saltstack-formulas/template-formula/commit/5a2bea8[5a2bea8^])
* *rtd:* add basic `index.rst` to allow RTD to produce docs
(https://github.com/saltstack-formulas/template-formula/commit/f02139f[f02139f^])
* *rtd:* use internal link targets at the top of each `.rst` file
(https://github.com/saltstack-formulas/template-formula/commit/da09528[da09528^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.7.6...v1.0.0++[1.0.0^] (2019-02-28)

=== Code Refactoring

* *components:* split components into separate subdirs
(https://github.com/saltstack-formulas/template-formula/commit/d957055[d957055^]),
closes
https://github.com//github.com/saltstack-formulas/template-formula/pull/48/issues/pullrequestreview-207182085[/github.com/saltstack-formulas/template-formula/pull/48#pullrequestreview-207182085^]
https://github.com//github.com/saltstack-formulas/template-formula/pull/48/issues/discussion_r259805312[/github.com/saltstack-formulas/template-formula/pull/48#discussion_r259805312^]
* *include+require:* use variable for duplicate values
(https://github.com/saltstack-formulas/template-formula/commit/4443518[4443518^])
* *pkg:* change to `package` instead
(https://github.com/saltstack-formulas/template-formula/commit/2cd82e5[2cd82e5^]),
closes
https://github.com//github.com/saltstack-formulas/template-formula/pull/48/issues/discussion_r259951123[/github.com/saltstack-formulas/template-formula/pull/48#discussion_r259951123^]
* *pkg:* move `pkg` related components into separate directory
(https://github.com/saltstack-formulas/template-formula/commit/c21f82b[c21f82b^])
* *states:* set state IDs based on a dependable structure
(https://github.com/saltstack-formulas/template-formula/commit/6690ee6[6690ee6^]),
closes
https://github.com//github.com/saltstack-formulas/template-formula/pull/48/issues/discussion_r259953473[/github.com/saltstack-formulas/template-formula/pull/48#discussion_r259953473^]
https://github.com//github.com/saltstack-formulas/template-formula/pull/48/issues/discussion_r259956996[/github.com/saltstack-formulas/template-formula/pull/48#discussion_r259956996^]
* *topdir:* use for `include` and `require` except `init.sls`
(https://github.com/saltstack-formulas/template-formula/commit/a218e91[a218e91^])
* *tpldir:* use `topdir` globally in place of `tpldir`
(https://github.com/saltstack-formulas/template-formula/commit/2838bc9[2838bc9^])
* *tplroot:* use `tplroot` instead of `topdir` to match `tpldata`
(https://github.com/saltstack-formulas/template-formula/commit/b7356b0[b7356b0^])

=== Continuous Integration

* *kitchen:* specify `image` explicitly for each platform
(https://github.com/saltstack-formulas/template-formula/commit/b25fbdc[b25fbdc^])
* *kitchen+travis:* use `debian:jessie-backports` as `debian-8`
(https://github.com/saltstack-formulas/template-formula/commit/1b9d249[1b9d249^]),
closes
https://github.com/saltstack-formulas/template-formula/issues/50[#50^]
https://github.com//github.com/saltstack/salt-pack/issues/657/issues/issuecomment-467932962[/github.com/saltstack/salt-pack/issues/657#issuecomment-467932962^]

=== Documentation

* *components:* update for separation of `pkg`, `config` & `service`
(https://github.com/saltstack-formulas/template-formula/commit/726fcab[726fcab^])
* *readme:* add suggested improvement to `template.service.clean`
(https://github.com/saltstack-formulas/template-formula/commit/bf1039c[bf1039c^])
* *readme:* fix typos
(https://github.com/saltstack-formulas/template-formula/commit/007159a[007159a^])

=== Features

* *pkg:* add `clean` states
(https://github.com/saltstack-formulas/template-formula/commit/422c7ac[422c7ac^])
* *pkg:* use `require` requisite between `pkg` states
(https://github.com/saltstack-formulas/template-formula/commit/6e7141b[6e7141b^]),
closes
https://github.com//github.com/saltstack/salt/blob/0c78d7dc894058988d171a28a11bd4a9dbf60266/salt/utils/jinja.py/issues/L120[/github.com/saltstack/salt/blob/0c78d7dc894058988d171a28a11bd4a9dbf60266/salt/utils/jinja.py#L120^]
https://github.com//github.com/saltstack/salt/blob/0c78d7dc894058988d171a28a11bd4a9dbf60266/salt/utils/templates.py/issues/L145[/github.com/saltstack/salt/blob/0c78d7dc894058988d171a28a11bd4a9dbf60266/salt/utils/templates.py#L145^]
https://github.com//github.com/saltstack/salt/issues/10838/issues/issuecomment-391718086[/github.com/saltstack/salt/issues/10838#issuecomment-391718086^]

=== Reverts

* *kitchen+travis:* disable `debian-8` due to `2019.2` bug
(https://github.com/saltstack-formulas/template-formula/commit/e8f0f7e[e8f0f7e^])

=== BREAKING CHANGES

* *states:* Wholesale state ID changes will break implementations that
are relying on the previous state IDs for requisite purposes.
* *pkg:* Changing the `pkg` directory to `package` will break
implementations that are depending on `pkg` for `include` or `sls`-based
requisite purposes.

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.7.5...v0.7.6++[0.7.6^] (2019-02-27)

=== Documentation

* *yaml:* os*.yaml map files needs at least an empty dict
(https://github.com/saltstack-formulas/template-formula/commit/dd99750[dd99750^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.7.4...v0.7.5++[0.7.5^] (2019-02-27)

=== Bug Fixes

* *pillar:* fix `os_family` typo
(https://github.com/saltstack-formulas/template-formula/commit/3f89c12[3f89c12^])
* *tofs:* update comments in `files_switch` macro for new method
(https://github.com/saltstack-formulas/template-formula/commit/3fa3640[3fa3640^])

=== Code Refactoring

* *macros:* use `tplroot` instead of `topdir` to match `tpldata`
(https://github.com/saltstack-formulas/template-formula/commit/923b459[923b459^])

=== Documentation

* *tofs:* add more sub-headings to ease document navigation
(https://github.com/saltstack-formulas/template-formula/commit/2c5dc21[2c5dc21^])
* *tofs:* apply language formatting to source code blocks
(https://github.com/saltstack-formulas/template-formula/commit/0638413[0638413^])
* *tofs:* explain how all parts of the `source` can be customised
(https://github.com/saltstack-formulas/template-formula/commit/2f82eb5[2f82eb5^]),
closes
https://github.com/saltstack-formulas/template-formula/issues/44[#44^]
* *tofs:* improve general use of language
(https://github.com/saltstack-formulas/template-formula/commit/5105d29[5105d29^])
* *tofs:* update the `files_switch` section for the updated macro
(https://github.com/saltstack-formulas/template-formula/commit/788f732[788f732^])
* *tofs:* use `{%-` for all Jinja statements
(https://github.com/saltstack-formulas/template-formula/commit/4348df8[4348df8^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.7.3...v0.7.4++[0.7.4^] (2019-02-27)

=== Continuous Integration

* *kitchen:* check for repos updates before trying package installation
(https://github.com/saltstack-formulas/template-formula/commit/b632383[b632383^])
* *kitchen+travis:* disable `debian-8` due to `2019.2` installation bug
(https://github.com/saltstack-formulas/template-formula/commit/178c710[178c710^])

=== Documentation

* *contributing:* separate `BREAKING CHANGE` under its own heading
(https://github.com/saltstack-formulas/template-formula/commit/ee053d7[ee053d7^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.7.2...v0.7.3++[0.7.3^] (2019-02-25)

=== Bug Fixes

* *tofs:* use `tpldir` derivative `topdir` for pillar (config) paths
(https://github.com/saltstack-formulas/template-formula/commit/5e9df00[5e9df00^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.7.1...v0.7.2++[0.7.2^] (2019-02-24)

=== Code Refactoring

* *tpldir:* use `tpldir` or derivatives to make formula portable
(https://github.com/saltstack-formulas/template-formula/commit/52d03d8[52d03d8^]),
closes
https://github.com/saltstack-formulas/template-formula/issues/22[#22^]

=== Continuous Integration

* *kitchen:* improve comments about `opensuse` problems encountered
(https://github.com/saltstack-formulas/template-formula/commit/c246939[c246939^])
* *travis:* prevent `release` stage running for PRs
(https://github.com/saltstack-formulas/template-formula/commit/3a072c7[3a072c7^]),
closes
https://github.com//travis-ci.com/saltstack-formulas/template-formula/jobs/180068519/issues/L466[/travis-ci.com/saltstack-formulas/template-formula/jobs/180068519#L466^]
https://github.com//github.com/saltstack-formulas/template-formula/pull/42/issues/issuecomment-466446324[/github.com/saltstack-formulas/template-formula/pull/42#issuecomment-466446324^]

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.7.0...v0.7.1++[0.7.1^] (2019-02-24)

=== Continuous Integration

* *kitchen:* use `salt-minion` version of `opensuse` to ensure tests run
(https://github.com/saltstack-formulas/template-formula/commit/99b073a[99b073a^])

=== Documentation

* *changelog:* remove erroneous "closes" used by `semantic-release`
(https://github.com/saltstack-formulas/template-formula/commit/be4571d[be4571d^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.6.0...v0.7.0++[0.7.0^] (2019-02-23)

=== Features

* *tofs:* implement backwards-compatible TOFSv2 for configurability
(https://github.com/saltstack-formulas/template-formula/commit/068a94d[068a94d^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.5.0...v0.6.0++[0.6.0^] (2019-02-23)

=== Documentation

* *contributing:* add basic introductory text before the TOC
(https://github.com/saltstack-formulas/template-formula/commit/45ccaf6[45ccaf6^])
* *contributing:* modify quoted heading to prevent TOC inclusion
(https://github.com/saltstack-formulas/template-formula/commit/abcb6ef[abcb6ef^])
* *readme:* convert note into a heading
(https://github.com/saltstack-formulas/template-formula/commit/5f2d789[5f2d789^])

=== Features

* *toc:* use `markdown-toc` directly to update inline
(https://github.com/saltstack-formulas/template-formula/commit/a5bae1e[a5bae1e^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.4.0...v0.5.0++[0.5.0^] (2019-02-23)

=== Features

* *kitchen+travis:* add `opensuse-leap` after resolving issues
(https://github.com/saltstack-formulas/template-formula/commit/7614a3c[7614a3c^])
* *kitchen+travis:* conduct tests on a wider range of platforms
(https://github.com/saltstack-formulas/template-formula/commit/1348078[1348078^])

=== Tests

* *inspec:* update `supports` for all platforms added
(https://github.com/saltstack-formulas/template-formula/commit/42f93b3[42f93b3^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.3.6...v0.4.0++[0.4.0^] (2019-02-23)

=== Documentation

* *contributing:* centre-align version bump columns in table
(https://github.com/saltstack-formulas/template-formula/commit/a238cae[a238cae^])

=== Features

* *authors:* update automatically alongside `semantic-release`
(https://github.com/saltstack-formulas/template-formula/commit/8000098[8000098^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.3.5...v0.3.6++[0.3.6^] (2019-02-22)

=== Continuous Integration

* *travis:* include `commitlint` stage
(https://github.com/saltstack-formulas/template-formula/commit/6659a69[6659a69^])
* *travis:* remove obsolete check based on `$TRAVIS_TEST_RESULT`
(https://github.com/saltstack-formulas/template-formula/commit/6df9c95[6df9c95^])

=== Documentation

* *contributing:* update with sub-headings and `commitlint` details
(https://github.com/saltstack-formulas/template-formula/commit/ea2c9a4[ea2c9a4^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.3.4...v0.3.5++[0.3.5^] (2019-02-21)

=== Code Refactoring

* *kitchen:* prefer `kitchen.yml` to `.kitchen.yml`
(https://github.com/saltstack-formulas/template-formula/commit/3860bf9[3860bf9^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.3.3...v0.3.4++[0.3.4^] (2019-02-21)

=== Documentation

* *contributing:* add commit message formatting instructions
(https://github.com/saltstack-formulas/template-formula/commit/fb3d173[fb3d173^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.3.2...v0.3.3++[0.3.3^] (2019-02-20)

=== Documentation

* *changelog:* add missing entry under `v0.3.2`
(https://github.com/saltstack-formulas/template-formula/commit/50352b5[50352b5^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.3.1...v0.3.2++[0.3.2^] (2019-02-20)

=== Documentation

* *README:* remove gitchangelog
(https://github.com/saltstack-formulas/template-formula/commit/2fc85fc[2fc85fc^])
* *contributing:* create blank template
(https://github.com/saltstack-formulas/template-formula/commit/3633e8f[3633e8f^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.3.0...v0.3.1++[0.3.1^] (2019-02-20)

=== Documentation

* *changelog:* merge previous `rst` into new `md` format
(https://github.com/saltstack-formulas/template-formula/commit/2b4e485[2b4e485^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.2.0...v0.3.0++[0.3.0^] (2019-02-20)

=== Features

* *semantic-release:* configure for this formula
(https://github.com/saltstack-formulas/template-formula/commit/cbcfd75[cbcfd75^])

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.1.7...v0.2.0++[0.2.0^] (2019-02-17)

* Added a working testing scaffold and travis support. [Javier Bértoli]

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.1.6...v0.1.7++[0.1.7^] (2019-02-16)

=== Fix

* Typo in the installation instructions. [Niels Abspoel]

=== Other

* Update the changelog. [Niels Abspoel]
* Update README with link to install gitchangelog [Imran Iqbal]

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.1.5...v0.1.6++[0.1.6^] (2019-02-16)

* Add changelog generator. [Niels Abspoel]

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.1.4...v0.1.5++[0.1.5^] (2019-02-15)

* Prepare v0.1.5 [Imran Iqbal]
* Fix missing ')' [gmazrael]

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.1.3...v0.1.4++[0.1.4^] (2019-02-15)

* Replace obsolete VERSION file and replace with FORMULA file. [Imran
Iqbal]

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.1.2...v0.1.3++[0.1.3^] (2019-02-12)

* Updated changelog and version. [Alexander Weidinger]
* Map.jinja: use grains.filter_by instead of defaults.merge. [Alexander
Weidinger]
+
__________________________________________________________________________________________________
because defaults.merge does not work with salt-ssh.
https://github.com/saltstack/salt/issues/51605

Added osfingermap.yaml.
__________________________________________________________________________________________________

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.1.1...v0.1.2++[0.1.2^] (2019-02-12)

* Improve comments and examples in osfamilymap & osmap [Imran Iqbal]
* Fix map.jinja and add more OSes. [Imran Iqbal]

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.1.0...v0.1.1++[0.1.1^] (2019-02-10)

* Update. [Niels Abspoel]
* Update formula with map.jinja and style guide references, improve
README and VERSION. [Niels Abspoel]

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.0.9...v0.1.0++[0.1.0^] (2019-02-10)

* Examples must be consistent. [Daniel Dehennin]
+
________________________________________
The “template” is kept during rendering.
________________________________________
** TOFS_pattern.md: add “template” to rendered state.
** template/macros.jinja: ditoo.
* Remove double slash in generated salt URL. [Daniel Dehennin]
+
____________________________________________________________________________________________________________________
When the files are “full path” with leading slash “/”, the generated URL
contain a double slash because of the join.
____________________________________________________________________________________________________________________
** template/macros.jinja: remove leading slash before joining parts.
** TOFS_pattern.md: mirror changes of “macros.jinja”.
* Add an example for “ntp” of the use of “files_switch” [Daniel
Dehennin]
* Accept pillar separator in “files_switch” prefix. [Daniel Dehennin]
+
___________________________________
The prefix was used for 2 purposes:
___________________________________
** define the pillar prefix where to lookup “:files_switch”. It supports
the colon “:” separator to lookup in pillar subtree like “foo:bar”
** define the path prefix where to look for “files/”, It did not support
separator to lookup inside directory tree.
+
This patch only replace any colon “:” with “/” when looking up “files/”
directory, with the “foo:bar” prefix:
** lookup “foo:bar:files_switch” pillar to get list of grains to match
** lookup files under “salt://foo/bar/files/”
** TOFS_pattern.md: document the new use of “prefix” supporting colon
“:”.
** template/macros.jinja: transform any colon “:” in “prefix” by slash
“/” to lookup files.
* Make TOFS pattern example usable. [Daniel Dehennin]
+
___________________________________________________________________________________________
The example could not be used as-is. This commit improve conformity to
formula conventions.
___________________________________________________________________________________________
** TOFS_pattern.md: add missing commas “,” in “map.jinja” and extra one
to ease the addition of new entries. Import “map.jinja” in “init.sls”
and “conf.sls”. Declare descriptive state IDs. Use the “module.function”
notation. Use the “name” parameter.
* Cosmetics modification of TOFS pattern documentation. [Daniel
Dehennin]
** TOFS_pattern.md: add myself as modifier. Trim trailing whitespaces.
Separate titles from first paragraph.
* Switch template.config to TOFS pattern. [Daniel Dehennin]
* Import TOFS pattern from Zabbix formula. [Daniel Dehennin]

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.0.8...v0.0.9++[0.0.9^] (2019-02-10)

* Add VERSION file. [Karim Hamza]
* Add note about formula versioning. [Karim Hamza]

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.0.7...v0.0.8++[0.0.8^] (2019-02-10)

* Align with SaltStack official formulas doc page. [Denys Havrysh]
* Use https in the link to SaltStack documentation. [Denys Havrysh]

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.0.6...v0.0.7++[0.0.7^] (2019-02-10)

* Map.ninja: fix typos and leftover comments. [Marco Molteni]
* Remove whitespace in map.jinja comment. [Andrew Gabbitas]

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.0.5...v0.0.6++[0.0.6^] (2019-02-10)

* Improve style and jinja too match salt-formula. [Niels Abspoel]
* Propose new-ish formula style - defaults live in defaults.yml - map
jinja overrides by grain + merges pillar:lookup - split all contextually
similar states in their own files. [puneet kandhari]

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.0.4...v0.0.5++[0.0.5^] (2019-02-10)

* Change states to use short-dec style. [Seth House]
* Update CHANGELOG.rst. [Nitin Madhok]
* Update README.rst. [Nitin Madhok]
+
_______________
Fix broken link
_______________
* Fixing pillar to match the map file. [Forrest]
+
_________________________________
Map file and pillar didn't match.
_________________________________

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.0.3...v0.0.4++[0.0.4^] (2019-02-10)

* Add change log. [Antti Jokipii]

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.0.2...v0.0.3++[0.0.3^] (2019-02-10)

* Updated the license and readme to match our standards. [Forrest
Alvarez]
* Use map.jinja content in init.sls. [Eugene Vereschagin]
* Add map.jinja. [Eugene Vereschagin]

== link:++https://github.com/saltstack-formulas/template-formula/compare/v0.0.1...v0.0.2++[0.0.2^] (2019-02-10)

* Add link to Salt Formula documentation. [Eugene Vereschagin]
* Change extension from .md to .rst. [Eugene Vereschagin]

== link:++https://github.com/saltstack-formulas/template-formula/releases/tag/v0.0.1++[0.0.1^] (2019-02-10)

* Initial commit. [Lukas Erlacher]
